# Generated by Django 2.2.2 on 2019-06-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='Profile',
        ),
        migrations.AddField(
            model_name='adduser',
            name='FirstName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adduser',
            name='LastName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
