# Generated by Django 2.2.2 on 2019-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190625_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddUsers',
            new_name='AddUser',
        ),
    ]
